### ISSUE TITLE
Uncaught Error: .mont is undefined

### ISSUE THREAD

**Issue by meetmagdalene** [Metric/Less-Compile#6]
[Enter steps to reproduce below:]
1. ... I pressed Command-S to save the file and this error appeared. The file will not save.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [lesscompile](https://github.com/Metric/Less-Compile) package, v0.6.0
### Stack Trace

Uncaught Error: .mont is undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/node_modules/less/lib/less/parser.js:604

Error
    at new Parser (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
    at compile (/Users/MagdaleneBenson/.atom/packages/lesscompile/lib/lesscompile.coffee:21:18)
    at atom-workspace.atom.commands.add.core:save (/Users/MagdaleneBenson/.atom/packages/lesscompile/lib/lesscompile.coffee:63:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:06.6.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "csslint",
      "vim-mode"
    ],
    "themes": [
      "one-dark-ui",
      "an-old-hope-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
an-old-hope-syntax, v0.4.1
atom-beautify, v0.28.19
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
css-snippets, v0.9.0
docs-snippets, v0.8.0
editor-stats, v0.17.0
file-icons, v1.6.13
highlight-line, v0.11.0
javascript-snippets, v1.0.0
jshint, v1.8.3
less-compiler, v0.6.2
less-than-slash, v0.11.1
lesscompile, v0.6.0
linter, v1.11.3
linter-csslint, v1.1.0
meteor-api, v2.20.0
minimap, v4.19.0
php-getters-setters, v0.5.5
project-manager, v2.6.5
terminal-status, v1.6.8
underscorejs-snippets, v0.2.2

# Dev
No dev packages
```

**Comment by Metric** [comment]
The problem is because you also have lesscompile installed along with
less-compiler. They create a conflict, because they both try to modify the
global Function, so that new Function() can be used to eval stuff.
Uninstall one or the other, but don't use both at once. I can't say if
less-than-slash may or may not be causing a conflict, because I have never
used it.

**Comment by Metric** [comment]
Also, I am the author of Less-Compile and not Lesscompile. Lesscompile is
the one throwing the error and not my Less-Compile.

**Comment by Metric** [comment]
_bleep_ me. I forgot I named the package lesscompile in the package.json. Yeah, it would be less-compiler causing the conflict.

**Comment by meetmagdalene** [comment]
Thanks for your quick response, and sorry I had not gotten back to you sooner also. I had tried removing the other less compiler package like you suggested but it didn't fix the problem, so I just moved on without compiling for the moment.

Glad you found the issue so quickly too! Cheers

**Comment by Metric** [comment]
Can you share the file that is creating this error? It would help me
determine what is going wrong. But to me it looks like an undefined less
variable in your less file more so than an actual error with the compiler,
though I could be wrong.

**Comment by meetmagdalene** [comment]
The stack trace says it is this file: /Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/node_modules/less/lib/less/parser.js:604

Not one of mine. :-/ And I can't seem to access/find it in order to share it here. Does that file look familiar though?

**Comment by Metric** [comment]
Can you share your .less file that is causing this. That is what I meant. I
already know where parser.js is.
